title: Felix Immanuel Kalaiselvan # your name (or website title) here
logo: "/images/GitPng1.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A quick learning engineer with result-driven "get it done" attitude and with excellent logical & reasoning skills. Passionate about analyzing business requirements and data analysis.  
  <br><br>
  Also good in analyzing and gathering user stories and converting them into a technical requirement. Has a sound knowledge of Agile and Scrum.
  <br><br>
  <a href="##https://www.linkedin.com/in/feliximmanuel/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
